name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        
      - name: Mirror
        run: |
          git clone https://codeberg.org/verybinary/mohmoh-client temp
          cp -r temp/. ./
          rm -rf temp
          git add -A
          git commit -m "Mirror"
          git push
